# Generated by Django 4.0.10 on 2024-03-17 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('device_id', models.CharField(blank=True, max_length=40)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('debug_comment', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='timesheet/')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'On time'), (2, 'Late'), (3, 'Absent'), (4, 'On vacation'), (5, 'Day off'), (6, 'Future day'), (7, 'Beg off')], default=0)),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=64)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('is_remote', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='companies.role')),
            ],
            options={
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('is_night_shift', models.BooleanField(default=False)),
                ('is_remote', models.BooleanField(default=False)),
                ('week_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='companies.role')),
            ],
            options={
                'ordering': ('week_day',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_schedules', to='companies.department')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('role', 'day'), name='unique timesheet'),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.UniqueConstraint(fields=('role', 'week_day'), name='unique schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentschedule',
            unique_together={('department', 'week_day')},
        ),
    ]
