# Generated by Django 4.0.10 on 2024-03-17 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_type', models.IntegerField(choices=[(1, 'Другой.'), (10, 'Отсутствует.'), (2, 'Опоздание.'), (3, 'Позднее завершение дня.'), (4, 'Не выполнил вовремя задачу легкой сложности.'), (5, 'Не выполнил вовремя задачу средней сложности.'), (6, 'Не выполнил вовремя задачу высокой сложности.'), (7, 'Награда за выполнение задачи легкой сложности.'), (8, 'Награда за выполнение задачи средней сложности.'), (9, 'Награда за выполнение задачи высокой сложности.'), (11, 'Награда исполнителю чеклиста.'), (12, 'Штраф исполнителю за позднее исполнение чеклиста.'), (13, 'Штраф исполнителю за невыполнение чеклиста.'), (14, 'Награда проверяющему чеклиста.'), (15, 'Штраф проверяющему за несвоевременную проверку чеклиста.'), (16, 'Штраф проверяющему за игнорирование проверки чеклиста.')], default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('points', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='companies.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Другой.'), (10, 'Отсутствует.'), (2, 'Опоздание.'), (3, 'Позднее завершение дня.'), (4, 'Не выполнил вовремя задачу легкой сложности.'), (5, 'Не выполнил вовремя задачу средней сложности.'), (6, 'Не выполнил вовремя задачу высокой сложности.'), (7, 'Награда за выполнение задачи легкой сложности.'), (8, 'Награда за выполнение задачи средней сложности.'), (9, 'Награда за выполнение задачи высокой сложности.'), (11, 'Награда исполнителю чеклиста.'), (12, 'Штраф исполнителю за позднее исполнение чеклиста.'), (13, 'Штраф исполнителю за невыполнение чеклиста.'), (14, 'Награда проверяющему чеклиста.'), (15, 'Штраф проверяющему за несвоевременную проверку чеклиста.'), (16, 'Штраф проверяющему за игнорирование проверки чеклиста.')], default=1)),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
